CREATE TABLE categories (
    category_id SERIAL PRIMARY KEY,
    category_name VARCHAR (50)
)

INSERT INTO categories (category_name) VALUES 
('Action'),
('Adapted to Anime'),
('Adapted to Drama CD'),
('Adapted to Manga'),
('Adult'),
('Adventure'),
('Age Gap'),
('Boys Love'),
('Character Growth'),
('Chinese Novel'),
('Comedy'),
('Cooking'),
('Different Social Status'),
('Drama'),
('Ecchi'),
('English Novel'),
('Fantasy'),
('Female Protagonist'),
('Game'),
('Gender Bender'),
('Harem'),
('Historical'),
('Horror'),
('Incest'),
('Isekai'),
('Josei'),
('Korean Novel'),
('Magic'),
('Martial Arts'),
('Mature'),
('Mecha'),
('Military'),
('Misunderstanding'),
('Mystery'),
('Netorare'),
('One shot'),
('Otome Game'),
('Parody'),
('Psychological'),
('Reverse Harem'),
('Romance'),
('School Life'),
('Science Fiction'),
('Seinen'),
('Shoujo'),
('Shoujo ai'),
('Shounen'),
('Shounen ai'),
('Slice of Life'),
('Slow Life'),
('Sports'),
('Super Power'),
('Supernatural'),
('Suspense'),
('Tragedy'),
('Wars'),
('Web Novel'),
('Workplace'),
('Yuri');